version: "3.9"

services:
  web:
    build: .
    command: gunicorn healthcare_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: healthcare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword

volumes:
  postgres_data: