# Generated by Django 5.1.4 on 2024-12-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
